version: '3.8'

services:
  # 1. Database for User Service
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3303:3306"
    volumes:
      - user_db_data:/var/lib/mysql

  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product
      MYSQL_PASSWORD: productpass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3302:3306"
    volumes:
      - product_db_data:/var/lib/mysql

  # 2. Centralized Redis (All services will use this)
  copy-redis:
    image: redis:alpine
    container_name: redis-copy
    ports:
      - "6377:6379"

volumes:
  user_db_data:
  product_db_data: